### ISSUE TITLE
Encryption scheme issues

### ISSUE THREAD

**Issue by yahesh** [AdriDevelopsThings/OpenCDN#17]
The used encryption scheme [is AES-CFB](https://github.com/AdriDevelopsThings/OpenCDN/blob/0da554859780538effcf6fb68a18faf60f218ef7/resources/api/encryption.py#L41) which does not provide integrity protection. This means that a known-plaintext attack can be mounted on all stored files.

By default, the encryption key only contains the character set [`[A-Za-z0-9]`](https://github.com/AdriDevelopsThings/OpenCDN/blob/0da554859780538effcf6fb68a18faf60f218ef7/resources/api/encryption.py#L27) and by default has a length of [15 characters](https://github.com/AdriDevelopsThings/OpenCDN/blob/0da554859780538effcf6fb68a18faf60f218ef7/resources/config.py#L47). This leads to a key space of roughly 5,5×10²⁵. It is mixed with a server key through PBKDF2 which, by default, has a length of [5 characters](https://github.com/AdriDevelopsThings/OpenCDN/blob/0da554859780538effcf6fb68a18faf60f218ef7/resources/config.py#L75) only consisting of alphanumeric values as well, increasing the key space to roughly 2×10³⁴. This is well bellow the key space of AES-256 that is used here (ca. 1,2×10⁷⁷). Furthermore, the encryption key and server key are generated using the [`random.choice`](https://github.com/AdriDevelopsThings/OpenCDN/blob/0da554859780538effcf6fb68a18faf60f218ef7/resources/api/encryption.py#L27) method. According to the Python documentation [_"\[t\]he pseudo-random generators of this module should not be used for security purposes."_](https://docs.python.org/3/library/random.html)

The server key can be read from the configuration file. The encryption key is stored to disk as well [by being used as a path component](https://github.com/AdriDevelopsThings/OpenCDN/blob/0da554859780538effcf6fb68a18faf60f218ef7/resources/api/upload.py#L124), being protected by only [a single round](https://github.com/AdriDevelopsThings/OpenCDN/blob/0da554859780538effcf6fb68a18faf60f218ef7/resources/api/encryption.py#L36) of [SHA3-256](https://github.com/AdriDevelopsThings/OpenCDN/blob/0da554859780538effcf6fb68a18faf60f218ef7/resources/config.py#L49). On top of it, the encryption key is provided [within the URI](https://github.com/AdriDevelopsThings/OpenCDN/blob/0da554859780538effcf6fb68a18faf60f218ef7/resources/api/download.py#L22), meaning that it might sooner or later be written to the webserver log file.

**Comment by AdriDevelopsThings** [comment]
Hello,

thanks for your issue. 
1. Yes, AES-CFB is a bad encryption mode.
2. Keyspace: The point of the project is that you can share files fast in messages. We don't want very long URLs like Google Drive URLs. But I can make the server key bigger.
3. Yes, random.choice is not a secure random generator.
4. As I said in *2.* the point of the project is to fast share files. The key must be included in the URL. The server administrator have to disable server logs.

I forgot to archive the project. I will not fix the issue, but I will rewrite OpenCDN and pay attention to your reports.
